import './globals.css'
import {
  Inter,
  Poppins,
  Rubik
} from 'next/font/google'
import Navbar from './components/Navbar'

const rubik = Rubik({ subsets: ['latin'] })
// const inter = Inter({ subsets: ['latin'] })
// const poppins = Poppins({
//   subsets: ['latin'],
//   weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
// })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className} suppressHydrationWarning={true}>
        <Navbar />
        {children}
      </body>
    </html >
  )
}
